<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.0RT5omm' shared service.

return $this->privates['.service_locator.0RT5omm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\DefaultController::contact' => ['privates', '.service_locator.SEhsEZ5', 'get_ServiceLocator_SEhsEZ5Service.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.SOGscYu', 'get_ServiceLocator_SOGscYuService.php', true],
    'App\\Controller\\DefaultController:contact' => ['privates', '.service_locator.SEhsEZ5', 'get_ServiceLocator_SEhsEZ5Service.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.SOGscYu', 'get_ServiceLocator_SOGscYuService.php', true],
], [
    'App\\Controller\\DefaultController::contact' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\DefaultController:contact' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
