<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SEhsEZ5' shared service.

return $this->privates['.service_locator.SEhsEZ5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'mailer' => ['privates', 'App\\Contact\\Mailer', 'getMailerService.php', true],
], [
    'mailer' => 'App\\Contact\\Mailer',
]);
