<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\LayoutController' shared autowired service.

include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once \dirname(__DIR__, 4).'/src/Controller/LayoutController.php';

$this->services['App\\Controller\\LayoutController'] = $instance = new \App\Controller\LayoutController();

$instance->setContainer(($this->privates['.service_locator.xIg1jiS'] ?? $this->load('get_ServiceLocator_XIg1jiSService.php'))->withContext('App\\Controller\\LayoutController', $this));

return $instance;
