<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Contact\Mailer' shared autowired service.

include_once \dirname(__DIR__, 4).'/src/Contact/Mailer.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/MailerInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Mailer.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport/TransportInterface.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport/Transports.php';
include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport.php';

return $this->privates['App\\Contact\\Mailer'] = new \App\Contact\Mailer('training@sensiolabs.com', new \Symfony\Component\Mailer\Mailer((new \Symfony\Component\Mailer\Transport(new RewindableGenerator(function () {
    yield 0 => ($this->privates['mailer.transport_factory.null'] ?? $this->load('getMailer_TransportFactory_NullService.php'));
    yield 1 => ($this->privates['mailer.transport_factory.sendmail'] ?? $this->load('getMailer_TransportFactory_SendmailService.php'));
    yield 2 => ($this->privates['mailer.transport_factory.smtp'] ?? $this->load('getMailer_TransportFactory_SmtpService.php'));
}, 3)))->fromStrings(['main' => $this->getEnv('MAILER_DSN')]), NULL, ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService())));
