framework:
    secret: '%env(APP_SECRET)%'
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    csrf_protection: ~
    #http_method_override: true
    #trusted_hosts: ~
    session:
        name: hangman_sess
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    #esi: ~
    #fragments: ~
    php_errors:
        log: true
