security:
    encoders:
        App\Entity\Player: auto

    providers:
        players:
            entity:
                class: App\Entity\Player
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        hangman:
            pattern: '^/'
            provider: players
            anonymous: true
            form_login:
                login_path: login
                check_path: login-check
                success_handler: App\Security\HangmanSuccessAuthenticationHandler
            logout:
                path: logout
                target: homepage
