index:
    path: /
    controller: 'Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction'
    defaults:
        path: '/%locale%'

login-check:
  path: '/auth/check'

logout:
  path: '/auth/forget'
