services:
    App\DataCollector\GameDataCollector:
        # should be autoWired (bug with data collector ?)
        arguments:
            $gameStorage: '@App\Game\Storage'
        tags:
            -
                name: data_collector
                id: hangman
                template: collector/hangman.html.twig
            -
                name: kernel.event_subscriber # should be autoConfigured by EventSubscriberInterface (bug with data collector ?)
