parameters:
    locale: 'en'
    app.allowed_locales_pattern: 'en|de|fr'
    app.mail_recipient: 'training@sensiolabs.com'

hangman:
    game:
        default_credits: 15

services:
    # _instanceof:
    #     App\Game\Loader\LoaderInterface:
    #         tags:
    #             name : hangman.loader
    #             #name : !php/const App\Kernel::HANGMAN_LOADER_TAG
    #             foo  : bar
    # default configuration only applies for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            # these are the scalar arguments used by service constructors. Instead of defining
            # the 'arguments' option for each service, you can define all once in this file
            $recipient: '%app.mail_recipient%'

    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Game/Exception,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Game\WordList:
        arguments:
            $dictionaries: '%hangman.game.dictionaries%'
        calls:
            - [addWord, [customer]]
            - [addWord, [lemonade]]
            - [addWord, [employee]]

    # App\Security\Voter\LegalAgeVoter:
    #     arguments:
    #         $legalAge: '%hangman.game.required_age%'

    App\Game\Listener\GameLogListener:
        $logger: '@monolog.logger.game'
