<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBAW6WJT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBAW6WJT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBAW6WJT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBAW6WJT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBAW6WJT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BAW6WJT',
    'container.build_id' => 'd623cc5b',
    'container.build_time' => 1575277519,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBAW6WJT');
