<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'homepage' => [['_locale'], ['_controller' => 'App\\Controller\\DefaultController::index'], ['_locale' => 'en|de|fr'], [['text', '/'], ['variable', '/', 'en|de|fr', '_locale']], [], []],
    'contact' => [['_locale'], ['_controller' => 'App\\Controller\\DefaultController::contact'], ['_locale' => 'en|de|fr'], [['text', '/contact'], ['variable', '/', 'en|de|fr', '_locale']], [], []],
    'game_home' => [['_locale'], ['_controller' => 'App\\Controller\\GameController::home'], ['_locale' => 'en|de|fr'], [['text', '/game/'], ['variable', '/', 'en|de|fr', '_locale']], [], []],
    'game_won' => [['_locale'], ['_controller' => 'App\\Controller\\GameController::won'], ['_locale' => 'en|de|fr'], [['text', '/game/won'], ['variable', '/', 'en|de|fr', '_locale']], [], []],
    'game_failed' => [['_locale'], ['_controller' => 'App\\Controller\\GameController::failed'], ['_locale' => 'en|de|fr'], [['text', '/game/failed'], ['variable', '/', 'en|de|fr', '_locale']], [], []],
    'game_reset' => [['_locale'], ['_controller' => 'App\\Controller\\GameController::reset'], ['_locale' => 'en|de|fr'], [['text', '/game/reset'], ['variable', '/', 'en|de|fr', '_locale']], [], []],
    'game_play_letter' => [['_locale', 'letter'], ['_controller' => 'App\\Controller\\GameController::playLetter'], ['letter' => '[A-Z]', '_locale' => 'en|de|fr'], [['variable', '/', '[A-Z]', 'letter'], ['text', '/game/play'], ['variable', '/', 'en|de|fr', '_locale']], [], []],
    'game_play_word' => [['_locale'], ['_controller' => 'App\\Controller\\GameController::playWord'], ['_locale' => 'en|de|fr'], [['text', '/game/play'], ['variable', '/', 'en|de|fr', '_locale']], [], []],
    'login' => [['_locale'], ['_controller' => 'App\\Controller\\SecurityController::login'], ['_locale' => 'en|de|fr'], [['text', '/login'], ['variable', '/', 'en|de|fr', '_locale']], [], []],
    'register' => [['_locale'], ['_controller' => 'App\\Controller\\SecurityController::register'], ['_locale' => 'en|de|fr'], [['text', '/register'], ['variable', '/', 'en|de|fr', '_locale']], [], []],
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'index' => [[], ['path' => '/en', '_controller' => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\RedirectController::urlRedirectAction'], [], [['text', '/']], [], []],
    'login-check' => [[], [], [], [['text', '/auth/check']], [], []],
    'logout' => [[], [], [], [['text', '/auth/forget']], [], []],
];
